/* ALTERANDO TABELAS */

CREATE TABLE TABELA (
    COLUNA1 VARCHAR(30),
    COLUNA2 VARCHAR(30),
    COLUNA3 VARCHAR(30)
);

/* ADICIONANDO UMA PRIMARY KEY
    Obs.: ao add primary key depois da criação da tabela
    não será possível add AUTO_INCREMENT. */
ALTER TABLE TABELA
    ADD PRIMARY KEY (COLUNA1);

/* ADICIONANDO UMA COLUNA SEM POSIÇÃO ELA VAI PARA ÚLTIMA POSIÇÃO */
ALTER TABLE TABELA
    ADD COLUNA4 VARCHAR(30);

/* ADICIONANDO COLUNA COM POSIÇÃO */
ALTER TABLE TABELA
    ADD COLUMN COLUNA5 VARCHAR(30) NOT NULL UNIQUE
    AFTER COLUNA4;

/* MODIFICANDO O TIPO DE UM CAMPO */
ALTER TABLE TABELA
    MODIFY COLUNA2 DATE NOT NULL;

/* RENOMEANDO O NOME DE UMA TABELA */
ALTER TABLE TABELA
    RENAME PESSOA;

CREATE TABLE TIME (
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    TIME VARCHAR(30),
    ID_PESSOA VARCHAR(30)
);

/* ADICIONANDO UMA FOREIGN KEY */
ALTER TABLE TIME
    ADD FOREIGN KEY(ID_PESSOA)
    REFERENCES PESSOA(COLUNA1);

/* VERIFICANDO FOREIGN KEY NUMA TABELA */
SHOW CREATE TABLE TIME;
