/* ORGANIZAÇÃO DE CHAVES */
CREATE TABLE JOGADOR(
    IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)
);

CREATE TABLE TIMES(
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    NOMETIME VARCHAR(30),
    ID_JOGADOR INT,
    FOREIGN KEY(ID_JOGADOR)
    REFERENCES JOGADOR(IDJOGADOR)
);

INSERT INTO JOGADOR VALUES (NULL,'GUERRERO');
INSERT INTO TIMES VALUES (NULL,'FLAMENGO',1);

SHOW CREATE TABLE JOGADOR;
SHOW CREATE TABLE TIMES;/*
| TIMES | CREATE TABLE `TIMES` (
  `IDTIME` int NOT NULL AUTO_INCREMENT,
  `NOMETIME` varchar(30) DEFAULT NULL,
  `ID_JOGADOR` int DEFAULT NULL,
  PRIMARY KEY (`IDTIME`),
  KEY `ID_JOGADOR` (`ID_JOGADOR`),
  CONSTRAINT `TIMES_ibfk_1` FOREIGN KEY (`ID_JOGADOR`) REFERENCES `JOGADOR` (`IDJOGADOR`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci | */

/* OBSERVAÇÃO:
    É UMA BOA PRÁTICA ADICIONAR AS CHAVES ESTRANGEIRAS
    DEPOIS DA CRIAÇÃO DAS TABELAS PARA PODER NOMEAR
    AS CONSTRAINTS. */
