/* ORGANIZANDO AS CHAVES E AÇÕES DE CONSTRAINTS */
/* CRIE PRIMEIRO AS TABELAS PARA DEPOIS ADICIONAR AS FOREIGN KEY */

SHOW TABLES;

DROP TABLE endereco;
DROP TABLE telefone;
DROP TABLE cliente;

CREATE TABLE CLIENTE(
    IDCLIENTE INT,
    NOME VARCHAR(10) NOT NULL
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT,
    TIPO CHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT
);

/* ADICIONANDO CHAVE PRIMÁRIA */
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
    PRIMARY KEY(IDCLIENTE);

/* ADICIONANDO CHAVE ESTRANGEIRA */
ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

/* VERIFICANDO NOME DA CONSTRAINTS */
SHOW CREATE TABLE TELEFONE;/*
| TELEFONE | CREATE TABLE `TELEFONE` (
  `IDTELEFONE` int DEFAULT NULL,
  `TIPO` char(3) NOT NULL,
  `NUMERO` varchar(10) NOT NULL,
  `ID_CLIENTE` int DEFAULT NULL,
  KEY `FK_CLIENTE_TELEFONE` (`ID_CLIENTE`),
  CONSTRAINT `FK_CLIENTE_TELEFONE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`IDCLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |*/

/* DICIONÁRIO DE DADOS */

SHOW DATABASES;

USE INFORMATION_SCHEMA;
STATUS;

/* TABELAS PARA FAZER BUSCAS */
SHOW TABLES;

DESC TABLE_CONSTRAINTS;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
    TABLE_NAME AS "TABELA",
    CONSTRAINT_TYPE AS "TIPO"
    FROM TABLE_CONSTRAINTS;
