/* CRIANDO PROCEDURES COMO REGRA DE NEGÓCIO */

/* PROCEDURE DE CADASTRO EM DUAS TABELAS */
CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE, @TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
    DECLARE @FK INT

    INSERT INTO PESSOA VALUES(@NOME,@SEXO,@NASCIMENTO)

    SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY) /* GERA UM ID */

    INSERT INTO TELEFONE VALUES (@TIPO, @NUMERO, @FK)
GO

CADASTRO 'JORGE', 'M', '1981-01-01', 'CEL', '98099809'
GO

SELECT PESSOA.*, TELEFONEPESSOA.*
    FROM PESSOA
    INNER JOIN TELEFONEPESSOA
    ON IDPESSOA = ID_PESSOA
GO


/* 
    EXEMPLO DE IDENTITY
    - GUARDA ÚLTIMO IDENTITY INSERIDO NA SEÇÃO
*/
INSERT INTO PESSOA VALUES('FAMAR','F','1989-11-6') /*[ÚLTIMO INSERT DA SEÇÃO] */
GO

SELECT @@IDENTITY
GO
