CREATE DATABASE ORCL
    USER SYS IDENTIFIED BY sys_password
    USER SYSTEM IDENTIFIED BY system_password
    LOGFILE GROUP 1 ('/opt/oracle/oradata/redo01.log') SIZE 100M,
            GROUP 2 ('/opt/oracle/oradata/redo02.log') SIZE 100M
    MAXLOGFILES 5
    MAXLOGMEMBERS 5
    MAXLOGHISTORY 1
    MAXDATAFILES 100
CHARACTER SET AL32UTF8
    NATIONAL CHARACTER SET AL16UTF16
    EXTENT MANAGEMENT LOCAL
    DATAFILE '/opt/oracle/oradata/system01.dbf' SIZE 325M REUSE
    SYSAUX DATAFILE '/opt/oracle/oradata/sysaux01.dbf' SIZE 325M REUSE
DEFAULT TABLESPACE users
    DATAFILE '/opt/oracle/oradata/users01.dbf'
SIZE 500M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
DEFAULT TEMPORARY TABLESPACE temp
    TEMPFILE '/opt/oracle/oradata/temp01.dbf'
SIZE 20M REUSE
    UNDO TABLESPACE UNDOTBS1
    DATAFILE '/opt/oracle/oradata/UNDOTBS1.dbf'
SIZE 200M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;