/*
    - O TRIGGER É ACIONADO DE ACORDO COM A TABELA
    QUE ELE É CONFIGURADO.
    - PODE SER UTILIZADO PARA VÁRIAS SOLUÇÕES.
    - COMO UTILIZA ';' NO BLOCO DE PROGRAMAÇÃO [BEGIN/END]
    É NECESSÁRIO ALTERAR O DELIMITADOR ANTES DA CRIAÇÃO
    DOS TRIGGERS E FINALIZANDO COM O DILIMITADOR ESCOLHIDO.
*/

CREATE TRIGGER NOME

/* DISPARA ANTES OU DEPOIS DE UMA OPERAÇÃO NA TABELA */
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
             /* OPERAÇÃO E TABELA QUE ACIONA O TRIGGER */

FOR EACH ROW (PARA CADA LINHA) /* PADRÃO PARA CRIAÇÃO DE TRIGGERS */

/* INICIO E FIM DO COMANDO QUE VAI SER ACIONADO NA CHAMADA DO TRIGGER */
BEGIN
    QUALQUER COMANDO SQL
END

/* MODELO PARA TRIGGERS SEM COMENTÁRIOS */
CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN
    QUALQUER COMANDO SQL;
END

/* VER TRIGGERS CONFIGURADAS NO BANCO DE DADOS COM DICIONÁRIO DE DADOS. */
SHOW DATABASES;
USE information_schema;
DESC TRIGGERS;
