/* AMBIENTE PARA TRIGGERS NA PRÁTICA */
CREATE DATABASE AULA40
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_520_ci;
USE AULA40;

CREATE TABLE USUARIO(
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    LOGIN VARCHAR(30),
    SENHA VARCHAR(100)
);

CREATE TABLE BKP_USUARIO(
    IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
    IDUSUARIO INT,
    NOME VARCHAR(30),
    LOGIN VARCHAR(30)
);

/* CRIANDO A PRIMEIRA TRIGGER */
/* NÃO ESQUECER DE ALTERAR O DELIMITADOR */
/*
    - NÃO É POSSÍVEL CRIAR DOIS TRIGGERS PARA
    A MESMA TABELA E TEMPO [BEFORE][AFTER].

    - [NEW] [OLD]
    UM DADO INSERIDO É [NEW]
    UM DADO DELETADO É [OLD]
    NO UPDATE:
    O DADO ANTIGO É [OLD]
    O NOVO DADO É [NEW]
*/

/*
    TRIGGER PARA DADOS DELETADOS NA TABELA
    USUARIO, ANTES DE DELETAR OS DADOS É SALVO UM BACKUP
    TABELA BKP_USUARIO.
*/
DELIMITER $;

CREATE TRIGGER BACKUP_USER
    BEFORE DELETE ON USUARIO
    FOR EACH ROW
    BEGIN
        INSERT INTO BKP_USUARIO
            VALUES(NULL,OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
    END
$

INSERT INTO USUARIO VALUES (NULL, 'ANDRADE', 'ANDRADE2009', 'HEXACAMPEÃO');

/*
    ANTES DOS DADOS SEREM DELETADOS ELES
    SÃO SALVOS NA TABELA BKP_USUARIO.
*/
DELETE FROM USUARIO WHERE IDUSUARIO = 1;

SELECT * FROM BKP_USUARIO;/*
+----------+-----------+---------+-------------+
| IDBACKUP | IDUSUARIO | NOME    | LOGIN       |
+----------+-----------+---------+-------------+
|        1 |         1 | ANDRADE | ANDRADE2009 |
+----------+-----------+---------+-------------+*/
