/*
    EVENTOS DE UMA TRIGGER
    AFTER | BEFORE | INSERT | DELETE | UPDATE
*/

/*
    ADICIONANDO COLUNA NA TABELA BKP_PRODUTO
    DO BANCO BACKUP CONECTADO DE OUTRO BANCO.
*/

ALTER TABLE BACKUP.BKP_PRODUTO
    ADD EVENTO CHAR(1);

SELECT * FROM BACKUP.BKP_PRODUTO;

/* 
    CRIANDO TRIGGER REGISTRANDO EVENTOS.
    POR SE TRATAR DE UM BANCO DE BACKUP E A TABELA
    RECEBER DADOS DE MAIS DE UM TRIGGER OS EVENTOS
    SERÃO REGISTRADOS NA COLUNA EVENTO COM SUAS INICIAIS.
*/

/* DELETANDO TRIGGER ANTIGA */
DROP TRIGGER BACKUP_PRODUTO_DEL;

/* NOVA TRIGGER COM COLUNA EVENTO */
DELIMITER $
CREATE TRIGGER BACKUP_PRODUTO_DEL
    BEFORE DELETE ON PRODUTO
    FOR EACH ROW
    BEGIN
        INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, 'D');
    END$
DELIMITER ;

DELETE FROM PRODUTO WHERE IDPRODUTO = 5;


