/* TRIGGER DE AUDITORIA */

/*
    APAGANDO BASES DAS AULAS ANTERIORES PARA
    CRIAR UM NOVO AMBIENTE.
*/

DROP DATABASE LOJA;
DROP DATABASE BACKUP;

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO (
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES(NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO BI',80.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO ORACLE',70.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO SQL SERVER',100.00);

CREATE DATABASE BACKUP;
USE BACKUP;

CREATE TABLE PRODUTO (
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    VALOR FLOAT(10,2)
);

/*
    CRIAÇÃO DO BANCO BACKUP PARA AUDITAR
    BANCO PRINCIPAL.
*/

CREATE DATABASE BACKUP;
USE BACKUP;

/* FUNÇÕES ÚTEIS PARA AUDITAR BANCOS E TABELAS */
/* QUANDO */
SELECT NOW();
/* QUEM */
SELECT CURRENT_USER();

CREATE TABLE BKP_PRODUTO (
    IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUTO INT,
    NOME VARCHAR(30),
    VALOR_ORIGINAL FLOAT(10,2),
    VALOR_ALTERADO FLOAT(10,2),
    DATA DATETIME,
    USUARIO VARCHAR(30),
    EVENTO CHAR(1)
);

USE LOJA;
SELECT * FROM PRODUTO;

/* CRIANDO TRIGGER PARA AUDITAR  OUTRO BANCO DE DADOS */

/*
    - NÃO ESQUECER DE ALTERAR O DELIMITER.
    - NÃO ESQUECER DE CONCATENAR COM '.' PARA PODER
    PROGRAMAR EM OUTRO BANCO.
    - ATENÇÃO AOS TEMPOS DO TRIGGER.
*/

DELIMITER $
CREATE TRIGGER AUDIT_PROD
    AFTER UPDATE ON PRODUTO
    FOR EACH ROW
    BEGIN
        INSERT INTO BACKUP.BKP_PRODUTO
            VALUES(NULL,OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U');
    END$

DELIMITER ;

/*
    FAZENDO ALTERAÇÃO NA TABELA PRODUTO DO BANCO LOJA,
    E CONFERINDO NA TABELA BKP_PRODUTO DO BANCO BACKUP.
*/

UPDATE PRODUTO SET VALOR = 110.00
    WHERE IDPRODUTO = 4;

SELECT * FROM BACKUP.BKP_PRODUTO;/*
+----------+-----------+------------------+----------------+----------------+---------------------+----------------+--------+
| IDBACKUP | IDPRODUTO | NOME             | VALOR_ORIGINAL | VALOR_ALTERADO | DATA                | USUARIO        | EVENTO |
+----------+-----------+------------------+----------------+----------------+---------------------+----------------+--------+
|        1 |         4 | LIVRO SQL SERVER |         100.00 |         110.00 | 2023-08-25 21:40:03 | root@localhost | U      |
+----------+-----------+------------------+----------------+----------------+---------------------+----------------+--------+*/
