/*  STORED PROCEDURE */
    SELECT 'PEREIRA';

/*  PARA CRIAR UMA STORED PROCEDURE É IMPORTANTE ALTERAR
    O DELIMITER PARA QUE O MYSQL CONSIGA INTERPRETAR
    O BLOCO DE INSTRUÇÃO E NÃO PARAR NO MEIO DA LEITURA */

/*  SINTAXE */
    DELIMITER $ 
    CREATE PROCEDURE NOME()
    BEGIN
        'QUALQUER PROCEDURE'
    END
    $

    DELIMITER $
    CREATE PROCEDURE NOME_EMPRESA()
    BEGIN
        SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;
    END
    $

/*  CHAMANDO UMA PROCEDURE */

    CALL NOME_EMPRESA()$

/*  ALTERE NOVAMENTE O DELIMITER PARA CHAMAR A PROCEDURE. 
    SEMPRE LEMBRE DE ALTERAR ANTES E DEPOIS DE CHAMAR
    A PROCEDURE */
    DELIMITER ;

    CALL NOME_EMPRESA();

/*  PROCEDURES COM PARAMETROS */
    DELIMITER $
    CREATE PROCEDURE CONTA()
    BEGIN
        SELECT 10 + 10 AS CONTA;
    END
    $

    DELIMITER ;
    CALL CONTA();
    DROP PROCEDURE CONTA;

    DELIMITER $
    CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
    BEGIN
        SELECT NUMERO1 + NUMERO2 AS CONTA;
    END
    $
    DELIMITER ;
    CALL CONTA(100,50);/*
    +-------+
    | CONTA |
    +-------+
    |   150 |
    +-------+*/
