/*  PROCEDURES */
/*  CRIA BANCO DE DADOS */
    CREATE DATABASE PROJETO;

/*  SELECIONA BANCO DE DADOS RECÉM CRIADO */
    USE PROJETO;

/*  CRIA TABELA NO BANCO DE DADOS PROJETO */
    CREATE TABLE CURSOS(
        IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
        NOME VARCHAR(30) NOT NULL,
        HORAS INT(3) NOT NULL,
        VALOR FLOAT(10,2) NOT NULL
    );

/*  INSERE DADOS NA TABELA CURSOS DO BANCO DE DADOS PROJETO */
    INSERT INTO CURSOS 
        VALUES(NULL, 'JAVA', 30, 500.00);

    INSERT INTO CURSOS
        VALUES(NULL, 'FUNDAMENTOS DE BANCO DE DADOS', 40, 700.00);

/*  PROJETA OS DADOS RECÉM INSERIDOS */
    SELECT * FROM CURSOS;

/*  ALTERA DELIMETER PARA POSSIBILITAR A CRIAÇÃO DA PROCEDURE */
    DELIMITER #

/*  COMANDO PARA VERIFICAR SE DELIMITER FOI ALTERADO */
    STATUS

/*  CRIA PROCEDURE COM PARAMETROS
    MANEIRA MAIS SEGURA DE FAZER INSERÇÕES NAS APLICAÇÕES WEB
    1. criar procedure 
    2. chamar procedure na regra de negócio */
    CREATE PROCEDURE CAD_CURSO(
        P_NOME VARCHAR(30),
        P_HORAS INT(3),
        P_PRECO(10,2))
    BEGIN
        INSERT INTO CURSOS
            VALUES(P_NOME, P_HORAS, P_PRECO);
    END
    #

/*  ALTERA NOVAMENTE O DELIMITER PARA O PADRÃO */
    DELIMITER ;

/*  CHAMA PROCEDURE */
    CALL CAD_CURSOS('BI SQL SERVER', 35, 3000.00);
    CALL CAD_CURSOS('POWER BI', 20, 1000.00);
    CALL CAD_CURSOS('TABLEAU', 30, 1200.00);
