/*
    PARTICIONANDO BANCO DE DADOS FISICAMENTE
    ORGANIZAR FISICAMENTE E LOGICAMENTE UM BANCO DE DADOS

        1 - CRIAR BANCO DE DADOS COM ARQUIVOS PARA OS SETORES
        DE MKT E RH.
        2 - CRIAR UM ARQUIVO PARA OS OUTROS DADOS EM GERAL.
        3 - DEIXAR O ARQUIVO MDF APENAS PARA O DICIONÁRIO DE DADOS.
        4 - CRIAR 2 GRUPOS DE ARQUIVOS [TODO GRUPO CRIADO TEM
        UM PRIMARY GROUP - MDF]

        CRIAR GRUPOS:
            PRIMARY - DEFAULT
            GA_MARKETING
            GA_VENDAS
            GA_GERAL - TORNAR PADRÃO      
*/

CREATE TABLE TB_EMPRESA (
    ID INT,
    NOME VARCHAR(50)
)
GO
