/*
    ARQUIVOS MDF [MASTER DATA FILE] E LDF [LOG DATA FILE]
        - É O FORMATO DOS ARQUIVOS DOS BANCOS
        DE DADOS CRIADOS NO SQL SERVER QUE FICAM SALVOS
        NAS PARTIÇÕES DO HD. ESSES LOCAIS ONDE OS ARQUIVOS
        SÃO SALVOS, TAMBÉM PODEM SER ALTERADOS.

        - ATOMICIDADE: REQUER QUE UM GRUPO DE TRANSAÇÕES
        SEJAM INDIVISÍVEIS.

        - TODAS AS TRANSAÇÕES SÃO GRAVADAS NOS ARQUIVOS LDF
        PARA ENTÃO PODEREM SEREM GRAVADAS COM O COMMIT,
        PODENDO REVERTER AO ESTADO ANTERIOR COM O COMANDO ROLLBACK.

        BEGIN
        SELECT
        COMMIT
        ROLLBACK

        - É RECOMENDADO MANTER OS ARQUIVOS DO SISTEMA COMO MDF
        E CRIAR GRUPOS DE ARQUIVOS [NDF] PARA PERSISTIR OS DADOS.

        - NOVAS TABELAS PODEM SEM GRAVADAS EM GRUPOS E PARTIÇÕES
        DIFERENTES PARA MELHORAR O GERENCIAMENTO DOS DADOS.
*/
