/*
    INTRODUÇÃO A TSQL - CAST E CONVERT PARA PADRÕES DE DATAS
    - TSQL É UM BLOCO DE PROGRAMAÇÃO.
    - ESSAS UNIDADES DE PROGRAMAS PODEM SER CHAMADAS DE BLOCOS ANÔNIMOS.
    - BLOCOS ANÔNIMOS NÃO RECEBEM NOMES E NÃO SÃO SALVOS NO BANCO DE DADOS.
    - ESSES BLOCOS ANÔNIMOS SÃO GERALMENTE UTILIZADOS PARA ALGO QUE
    VAI UTILIZADO UMA VEZ OU PARA TESTES.
*/

/* UM BLOCO TSQL */
BEGIN
    PRINT 'PRIMEIRO BLOCO'
END
GO

/* 
    BLOCOS DE ATRIBUIÇÃO DE VARIÁVEIS
    - UMA VARIÁVEL CONFIGURADA DENTRO DE UM BLOCO
    DE PROGRAMAÇÃO, NÃO PODE SER ACESSADA FORA
    DO BLOCO.
*/
 DECLARE
    @CONTADOR INT
BEGIN
    SET @CONTADOR = 5
    PRINT @CONTADOR
END
GO

/*
    NO SQL SERVER TUDO É TIPADO.
    PARA CONVERTER TIPOS NO SQL SERVER
    É UTILIZADO [CAST] PARA A MAIORIA DOS TIPOS
    E [CONVERT] PARA DATAS
*/

DECLARE
    @V_NUMERO NUMERIC(10,2) = 100.52,
    @V_DATA DATETIME = '20170207'
BEGIN
    PRINT 'VALOR NÚMERICO: [+] ' + CAST(@V_NUMERO AS VARCHAR)
    PRINT 'VALOR NÚMERICO: [+] ' + CONVERT(VARCHAR, @V_NUMERO)
    PRINT 'VALOR NÚMERICO: [+] ' + CAST(@V_DATA AS VARCHAR)
    PRINT 'VALOR NÚMERICO: [+] ' + CONVERT(VARCHAR, @V_DATA, 121)
    PRINT 'VALOR NÚMERICO: [+] ' + CONVERT(VARCHAR, @V_DATA, 120)
    PRINT 'VALOR NÚMERICO: [+] ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO/*
VALOR NÚMERICO: [+] 100.52
VALOR NÚMERICO: [+] 100.52
VALOR NÚMERICO: [+] Feb  7 2017 12:00AM
VALOR NÚMERICO: [+] 2017-02-07 00:00:00.000
VALOR NÚMERICO: [+] 2017-02-07 00:00:00
VALOR NÚMERICO: [+] 07-02-2017*/
