FROM postgres

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV LC_ALL POSIX

RUN apt-get update 
        # apt-get upgrade -y && \
        # apt-get install -y git && \
        # apt-get install -y nano && \
        # apt-get install -y net-tools && \
        # apt-get install -y unzip && \
        # apt-get install -y gzip && \
        # apt-get install -y apt-transport-https && \
        # apt-get install -y php8.2 && \
        # apt-get install -y apache2 && \
        # apt-get install -y php-pgsql 
        # apt-get install -y libicu-dev && \
        # apt-get install -y icu-devtools && \
        # apt-get install -y libpq-dev && docker-php-ext-install pdo pgsql pdo_pgsql && \
        # apt-get install -y php-pgsql && \
        # apt-get install -y libpq-dev && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && docker-php-ext-install pdo pdo_pgsql pgsql && docker-php-ext-enable pdo_pgsql && \
        # apt-get install -y curl && \
        # apt-get install -y openssl
        # apt-get install -y postgresql-all 
        # apt-get install -y build-essential && \
        # apt-get install -y locales
        # apt install -y php8.2-cli && \ 
        # apt install -y php8.2-common && \
        # apt install -y php8.2-zip && \
        # apt install -y php8.2-gd && \
        # apt install -y php8.2-mbstring && \
        # apt install -y php8.2-curl && \
        # apt install -y php8.2-xml && \
        # apt install -y php8.2-bcmath 

# RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
